[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.2.6"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "6.4.21"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/beevik/etree"
  version = "0.0.0"
